"""initial

Revision ID: 664f06c0124c
Revises: 
Create Date: 2026-03-30 04:13:09.288986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664f06c0124c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banas_cashiers',
    sa.Column('cashier_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('cashier_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('banas_categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('banas_customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('banas_discounts',
    sa.Column('discount_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('applies_to', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('discount_id')
    )
    op.create_table('banas_suppliers',
    sa.Column('supplier_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('banas_products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('barcode', sa.String(length=80), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['banas_categories.category_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['banas_suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('banas_purchase_orders',
    sa.Column('po_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['banas_cashiers.cashier_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['banas_suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_table('banas_sales',
    sa.Column('sale_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('amount_tendered', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('change_given', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['banas_cashiers.cashier_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['banas_customers.customer_id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_table('banas_po_items',
    sa.Column('po_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['banas_purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['banas_products.product_id'], ),
    sa.PrimaryKeyConstraint('po_item_id')
    )
    op.create_table('banas_sale_items',
    sa.Column('sale_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['banas_products.product_id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['banas_sales.sale_id'], ),
    sa.PrimaryKeyConstraint('sale_item_id')
    )
    op.create_table('banas_stock_movements',
    sa.Column('movement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('moved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['banas_cashiers.cashier_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['banas_products.product_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banas_stock_movements')
    op.drop_table('banas_sale_items')
    op.drop_table('banas_po_items')
    op.drop_table('banas_sales')
    op.drop_table('banas_purchase_orders')
    op.drop_table('banas_products')
    op.drop_table('banas_suppliers')
    op.drop_table('banas_discounts')
    op.drop_table('banas_customers')
    op.drop_table('banas_categories')
    op.drop_table('banas_cashiers')
    # ### end Alembic commands ###
